version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pranjal
      MYSQL_DATABASE: zenduty
      MYSQL_USER: pranjal
      MYSQL_PASSWORD: pranjal

    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A djangoProject1 worker --loglevel=info
    depends_on:
      - db
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    links:
      - db
  beats:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A djangoProject1 beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    links:
      - db

  redis:
    image: redis:6.0-alpine
    restart: always
